// <auto-generated />
namespace Odev.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.0")]
    public sealed partial class firstmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202501111922569_first-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
